# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anatoli Drumi
title: Linux System Administrator | DevSecOps
email: anatoli.drumi@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: imurd
instagram_username: imurd87
linkedin_username: drumit

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Anatoli and I'm a Linux system administrator. My experience in IT for over 10 years. Also, I spend my free time on pentest, on the HackTheBox site (this is a hobby), also, I have a little experience with GIT, CircleCI, Github Action, Amazon, Docker, Terraform, Ansible, Grafana and Datadog - tools that are often used by the DevOps Engineer. I have worked for several international companies. - AlliedTesting and Helium10. At AlliedTesting, I have an incredible experience of interacting with development and testing teams. My responsibilities were to maintain high security standards on the project, I also implemented Linux in the company, and integrated it into the infrastructure, taking into account all the company's standards. Also, I have been doing virtualization and containerization. I am most skilled in Linux and automation.

  I am happy when everything is standardized in the company on all steps and all policies are followed, this helps to avoid confusion and violations.
content:
 - title: Projects # Title for the section
        layout: list # Type of content section (list/text)
        content:
          - layout: top-middle
            title: Super awesome project
            link: github.com
            # link_text: Project Website
            additional_links:
              - title: sproogen/modern-resume-theme
                icon: fab fa-github
                url: github.com/sproogen/modern-resume-theme
              # - title:  Github page for project (eg. sproogen/modern-resume-theme)
              #   icon: fab fa-github
              #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
            quote: >
              This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
            description: | # this will include new lines to allow paragraphs
              I started this project as a way if learning <mark>React</mark> and i

  - title: Experience 
    layout: list  # Type of content section (list/text)
    content:
      - layout: left
        title: Helium10
        link: https://www.helium10.com
        sub_title: DevOps Engineer
        caption: Jul 2021 - Oct 2021
        quote: >
        I was involved in maintaining infrastructure, adding projects to amazon, configuring docker containers and monitoring
      - layout: left
        title: AlliedTesting
        link: https://www.alliedtesting.com
        sub_title: Systems Administrator
        caption: Jul 2019 - Jul 2021
        quote: >
        I administered systems, created and solved tasks, maintained infrastructure, implemented Linux, monitored compliance with security policies



- title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pridnestrovian State University
        caption: 2015 - 2020
        sub_title: Faculty Physicals and Mathematics

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks, Linux and security some of my other interests and hobbies are:
      - Jogging
      - Reading
      - Classical Music 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
