# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2
# Personal info
name: Anatoli Drumi
title: Linux System Administrator | DevSecOps
email: anatoli.drumi@gmail.com
# Dark Mode (true/false/never)
darkmode: never
# Social links
github_username: imurd
instagram_username: imurd87
linkedin_username: drumit

# Additional icon links
additional_links:
- title: PDF
  icon: https://imurd.github.io/images/pdf.jpg
  url: https://imurd.github.io/pdf/DevOps_Anatoli_Drumi.pdf

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Anatoli. My experience in IT for over 10 years. I'm a Linux system administrator. Also, I spend my free time on pentest, on the HackTheBox site (this is a hobby), also, I have some experience with Git, 
  CircleCI, Github Action, Amazon, Docker, Terraform, Ansible, Grafana and Datadog - tools that are often used by the DevOps Engineer. I have worked for several international companies - AlliedTesting and Helium10. At AlliedTesting, I have an incredible experience of interacting with development and testing teams. My responsibilities were to maintain high security standards on the project. Also, I have been doing virtualization and containerization. I am most skilled in Linux and automation.

  I am happy when everything is standardized in the company on all steps and all policies are followed, this helps to avoid confusion and violations.
content:
  - title: Experience 
    layout: list
    content:
      - layout: left
        title: Helium10
        link: https://www.helium10.com
        sub_title: DevOps Engineer
        caption: Jul 2021 - Oct 2021
        quote: I was involved in maintaining infrastructure, adding projects to Amazon, with Terraform and Git, and CircleCI, also, I created docker containers for developer environment that is identical to prod. environment. This helped not to "clog" the user's working machine with a large number of different versions of the same software. Also I did dashboard with SLO in Datadog for monitoring our websites, and monitoring docker containers
      - layout: left
        title: AlliedTesting
        link: https://www.alliedtesting.com
        sub_title: Systems Administrator
        caption: Jul 2019 - Jul 2021
        quote: I administered systems, created and solved tasks, maintained infrastructure, one of the my biggest projects was migration desktop OSs to Linux maintaining compatibility with the existing company policies and standards, it is enabling company flexibility and savings on the OS initial and ongoing costs. Also for good economy and high security, I created and maintained 2 Proxmox clusters with CI / CD. Also, I did documentation on the allowed software on projects and regularly participated in zoom conferences, where regularly trained and contributed to the training of colleagues
      - layout: left
        title: Active Computers
        link: https://www.acomps.ru
        caption: Mart 2017 - Jul 2019
        sub_title: Support Engineer | System Administrator
        quote: Support multiple clients and infrastructure in integrator company, Moscow
      - layout: left
        title: Court Department
        link: http://suddep.gospmr.org
        sub_title: Head of IT and System Engineer
        caption: Mart 2013 - Oct 2018
        quote: Build and support Windows and Linux infrastructure, manage IT Department. Specifically, I've created Active Directory Domain Controllers, Group Policy, Corporate Mail, and more. A DLP system has also been created and maintained. During my work, I contributed to onboarding and the acquisition of practical skills from several guys immediately after university. Created checklists and instructions to consistently maintain infrastructure and help users.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pridnestrovian State University
        caption: 2015 - 2020
        sub_title: Faculty Physicals and Mathematics
      - layout: left
        title: Zaoksky Adventist University
        caption: 2004 - 2007
        sub_title: Faculty of Theology

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks, Linux and security some of my other interests and hobbies are:
      - Jogging
      - Reading
      - Classical Music 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
