import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider, useMessages} from 'next-intl';
import Script from "next/script";
import {useEffect, useState} from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {

  const messages = useMessages();
  return (

    <html lang={locale}>
      <head>
        {/*<link rel="stylesheet" href="../../../static/plugin/bootstrap.min.css"/>*/}
        {/*<link rel="stylesheet" href="../../../static/plugin/style.css"/>*/}
        {/*<link rel="stylesheet" href="../../../static/plugin/themify-icons.css"/>*/}
        {/*<link rel="stylesheet" href="../../../static/plugin/owl.carousel.min.css"/>*/}
        {/*<link rel="stylesheet" href="../../../static/plugin/magnific-popup.css"/>*/}
        {/*<link rel="stylesheet" href="../../../static/plugin/master.css"/>*/}
          <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900" rel="stylesheet"/>
          <link rel="stylesheet" href="../../../static/css/bootstrap.min.css"/>
          {/*<link rel="stylesheet" href="../../../static/css/aos.css"/>*/}
          <link rel="stylesheet" href="../../../static/css/jquery.fancybox.min.css"/>
          <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css"/>
          <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css"/>
          <link rel="stylesheet" href="../../../static/css/style.css"/>



      </head>
      <body className={`${inter.className} home-1`}>
      <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
      </NextIntlClientProvider>

        {/*<Script src="../../../static/plugin/mad/js/vendor/modernizr-3.6.0.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/vendor/jquery-3.6.0.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/vendor/bootstrap.bundle.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/slick.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/countdown.min.js" strategy="lazyOnload" async></Script>*/}
        {/*/!*<Script src="../../../static/plugin/mad/js/plugins/nice-select.min.js"></Script>*!/*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/jqueryui.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/image-zoom.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/imagesloaded.pkgd.min.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/ajaxchimp.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/plugins/ajax-mail.js" strategy="lazyOnload" async></Script>*/}
        {/*<Script src="../../../static/plugin/mad/js/main.js" strategy="lazyOnload" async></Script>*/}
      </body>
    </html>
  );
}
